name: .NET Core 6 CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
jobs:
  build-and-deploye:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'  # Use .NET 6 SDK

    - name: Restore dependencies
      run: dotnet restore  # Restore the project's dependencies

    - name: Build
      run: dotnet build --configuration Release  # Build the project in Release mode

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish  # Publish the build artifacts

    - name: Upload React Build Files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "./publish/*"
        target: "/var/www/html/test-api"

